# Generated by Django 4.2.18 on 2025-04-29 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReportSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('day_of_week', models.PositiveSmallIntegerField(default=0, help_text='Day of the week to send report (0=Monday, 6=Sunday)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_report_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
